[package]
name = "fov-camera"
version = "0.1.0"
edition = "2024"
authors = [
    "Carsten Ramke <carsten.ramke@gmail.com>"
]

[dependencies]
slint = "1.10.0"

[build-dependencies]
slint-build = "1.10.0"